id: P008069
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18871
  title: ལྕགས་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    8fea73bb7df34be9ab0c0019851489e1:
      image_group_id: I8LS18873
      title: Volume 1 of lcags lam skor gyi krung hwa mi dmangs spyi mthun rgyal khab
        kyi bca' khrims/
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
