id: P008069
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18871
  title: ལྕགས་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    d6ae0b5c90e4462195fd8f6168c93fc7:
      image_group_id: I8LS18873
      title: ''
      volume_number: 1
      total_pages: 48
ebook_metadata:
  title: ལྕགས་ལམ་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  sku: P008069
  cover: cover.jpg
  layers:
  - pagination
